/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VVideoIdRouteImport } from './routes/v.$videoId'
import { Route as AuthenticatedUploadRouteImport } from './routes/_authenticated/upload'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedExploreRouteImport } from './routes/_authenticated/explore'
import { Route as AuthenticatedCameraRouteImport } from './routes/_authenticated/camera'
import { Route as AuthenticatedUUsernameRouteImport } from './routes/_authenticated/u.$username'
import { Route as AuthenticatedSettingsSecurityRouteImport } from './routes/_authenticated/settings.security'
import { Route as AuthenticatedSettingsPrivacyRouteImport } from './routes/_authenticated/settings.privacy'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings.notifications'
import { Route as AuthenticatedSettingsLanguageRouteImport } from './routes/_authenticated/settings.language'
import { Route as AuthenticatedSettingsEditProfileRouteImport } from './routes/_authenticated/settings.edit-profile'
import { Route as AuthenticatedSettingsDeleteAccountRouteImport } from './routes/_authenticated/settings.delete-account'
import { Route as AuthenticatedSettingsChangePasswordRouteImport } from './routes/_authenticated/settings.change-password'
import { Route as AuthenticatedUUsernameKindRouteImport } from './routes/_authenticated/u.$username.$kind'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VVideoIdRoute = VVideoIdRouteImport.update({
  id: '/v/$videoId',
  path: '/v/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUploadRoute = AuthenticatedUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExploreRoute = AuthenticatedExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCameraRoute = AuthenticatedCameraRouteImport.update({
  id: '/camera',
  path: '/camera',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUUsernameRoute = AuthenticatedUUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsSecurityRoute =
  AuthenticatedSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsPrivacyRoute =
  AuthenticatedSettingsPrivacyRouteImport.update({
    id: '/privacy',
    path: '/privacy',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsLanguageRoute =
  AuthenticatedSettingsLanguageRouteImport.update({
    id: '/language',
    path: '/language',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsEditProfileRoute =
  AuthenticatedSettingsEditProfileRouteImport.update({
    id: '/edit-profile',
    path: '/edit-profile',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsDeleteAccountRoute =
  AuthenticatedSettingsDeleteAccountRouteImport.update({
    id: '/delete-account',
    path: '/delete-account',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsChangePasswordRoute =
  AuthenticatedSettingsChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedUUsernameKindRoute =
  AuthenticatedUUsernameKindRouteImport.update({
    id: '/$kind',
    path: '/$kind',
    getParentRoute: () => AuthenticatedUUsernameRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/camera': typeof AuthenticatedCameraRoute
  '/explore': typeof AuthenticatedExploreRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/upload': typeof AuthenticatedUploadRoute
  '/v/$videoId': typeof VVideoIdRoute
  '/settings/change-password': typeof AuthenticatedSettingsChangePasswordRoute
  '/settings/delete-account': typeof AuthenticatedSettingsDeleteAccountRoute
  '/settings/edit-profile': typeof AuthenticatedSettingsEditProfileRoute
  '/settings/language': typeof AuthenticatedSettingsLanguageRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/privacy': typeof AuthenticatedSettingsPrivacyRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/u/$username': typeof AuthenticatedUUsernameRouteWithChildren
  '/u/$username/$kind': typeof AuthenticatedUUsernameKindRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/camera': typeof AuthenticatedCameraRoute
  '/explore': typeof AuthenticatedExploreRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/upload': typeof AuthenticatedUploadRoute
  '/v/$videoId': typeof VVideoIdRoute
  '/settings/change-password': typeof AuthenticatedSettingsChangePasswordRoute
  '/settings/delete-account': typeof AuthenticatedSettingsDeleteAccountRoute
  '/settings/edit-profile': typeof AuthenticatedSettingsEditProfileRoute
  '/settings/language': typeof AuthenticatedSettingsLanguageRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/privacy': typeof AuthenticatedSettingsPrivacyRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/u/$username': typeof AuthenticatedUUsernameRouteWithChildren
  '/u/$username/$kind': typeof AuthenticatedUUsernameKindRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/camera': typeof AuthenticatedCameraRoute
  '/_authenticated/explore': typeof AuthenticatedExploreRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/upload': typeof AuthenticatedUploadRoute
  '/v/$videoId': typeof VVideoIdRoute
  '/_authenticated/settings/change-password': typeof AuthenticatedSettingsChangePasswordRoute
  '/_authenticated/settings/delete-account': typeof AuthenticatedSettingsDeleteAccountRoute
  '/_authenticated/settings/edit-profile': typeof AuthenticatedSettingsEditProfileRoute
  '/_authenticated/settings/language': typeof AuthenticatedSettingsLanguageRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/settings/privacy': typeof AuthenticatedSettingsPrivacyRoute
  '/_authenticated/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/_authenticated/u/$username': typeof AuthenticatedUUsernameRouteWithChildren
  '/_authenticated/u/$username/$kind': typeof AuthenticatedUUsernameKindRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/camera'
    | '/explore'
    | '/feed'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/upload'
    | '/v/$videoId'
    | '/settings/change-password'
    | '/settings/delete-account'
    | '/settings/edit-profile'
    | '/settings/language'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/settings/security'
    | '/u/$username'
    | '/u/$username/$kind'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/camera'
    | '/explore'
    | '/feed'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/upload'
    | '/v/$videoId'
    | '/settings/change-password'
    | '/settings/delete-account'
    | '/settings/edit-profile'
    | '/settings/language'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/settings/security'
    | '/u/$username'
    | '/u/$username/$kind'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/camera'
    | '/_authenticated/explore'
    | '/_authenticated/feed'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/upload'
    | '/v/$videoId'
    | '/_authenticated/settings/change-password'
    | '/_authenticated/settings/delete-account'
    | '/_authenticated/settings/edit-profile'
    | '/_authenticated/settings/language'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/privacy'
    | '/_authenticated/settings/security'
    | '/_authenticated/u/$username'
    | '/_authenticated/u/$username/$kind'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VVideoIdRoute: typeof VVideoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$videoId': {
      id: '/v/$videoId'
      path: '/v/$videoId'
      fullPath: '/v/$videoId'
      preLoaderRoute: typeof VVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/upload': {
      id: '/_authenticated/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthenticatedUploadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/explore': {
      id: '/_authenticated/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AuthenticatedExploreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/camera': {
      id: '/_authenticated/camera'
      path: '/camera'
      fullPath: '/camera'
      preLoaderRoute: typeof AuthenticatedCameraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/u/$username': {
      id: '/_authenticated/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof AuthenticatedUUsernameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/security': {
      id: '/_authenticated/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthenticatedSettingsSecurityRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/privacy': {
      id: '/_authenticated/settings/privacy'
      path: '/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof AuthenticatedSettingsPrivacyRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/language': {
      id: '/_authenticated/settings/language'
      path: '/language'
      fullPath: '/settings/language'
      preLoaderRoute: typeof AuthenticatedSettingsLanguageRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/edit-profile': {
      id: '/_authenticated/settings/edit-profile'
      path: '/edit-profile'
      fullPath: '/settings/edit-profile'
      preLoaderRoute: typeof AuthenticatedSettingsEditProfileRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/delete-account': {
      id: '/_authenticated/settings/delete-account'
      path: '/delete-account'
      fullPath: '/settings/delete-account'
      preLoaderRoute: typeof AuthenticatedSettingsDeleteAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/change-password': {
      id: '/_authenticated/settings/change-password'
      path: '/change-password'
      fullPath: '/settings/change-password'
      preLoaderRoute: typeof AuthenticatedSettingsChangePasswordRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/u/$username/$kind': {
      id: '/_authenticated/u/$username/$kind'
      path: '/$kind'
      fullPath: '/u/$username/$kind'
      preLoaderRoute: typeof AuthenticatedUUsernameKindRouteImport
      parentRoute: typeof AuthenticatedUUsernameRoute
    }
  }
}

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsChangePasswordRoute: typeof AuthenticatedSettingsChangePasswordRoute
  AuthenticatedSettingsDeleteAccountRoute: typeof AuthenticatedSettingsDeleteAccountRoute
  AuthenticatedSettingsEditProfileRoute: typeof AuthenticatedSettingsEditProfileRoute
  AuthenticatedSettingsLanguageRoute: typeof AuthenticatedSettingsLanguageRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsPrivacyRoute: typeof AuthenticatedSettingsPrivacyRoute
  AuthenticatedSettingsSecurityRoute: typeof AuthenticatedSettingsSecurityRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsChangePasswordRoute:
    AuthenticatedSettingsChangePasswordRoute,
  AuthenticatedSettingsDeleteAccountRoute:
    AuthenticatedSettingsDeleteAccountRoute,
  AuthenticatedSettingsEditProfileRoute: AuthenticatedSettingsEditProfileRoute,
  AuthenticatedSettingsLanguageRoute: AuthenticatedSettingsLanguageRoute,
  AuthenticatedSettingsNotificationsRoute:
    AuthenticatedSettingsNotificationsRoute,
  AuthenticatedSettingsPrivacyRoute: AuthenticatedSettingsPrivacyRoute,
  AuthenticatedSettingsSecurityRoute: AuthenticatedSettingsSecurityRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedUUsernameRouteChildren {
  AuthenticatedUUsernameKindRoute: typeof AuthenticatedUUsernameKindRoute
}

const AuthenticatedUUsernameRouteChildren: AuthenticatedUUsernameRouteChildren =
  {
    AuthenticatedUUsernameKindRoute: AuthenticatedUUsernameKindRoute,
  }

const AuthenticatedUUsernameRouteWithChildren =
  AuthenticatedUUsernameRoute._addFileChildren(
    AuthenticatedUUsernameRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCameraRoute: typeof AuthenticatedCameraRoute
  AuthenticatedExploreRoute: typeof AuthenticatedExploreRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedUploadRoute: typeof AuthenticatedUploadRoute
  AuthenticatedUUsernameRoute: typeof AuthenticatedUUsernameRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCameraRoute: AuthenticatedCameraRoute,
  AuthenticatedExploreRoute: AuthenticatedExploreRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedUploadRoute: AuthenticatedUploadRoute,
  AuthenticatedUUsernameRoute: AuthenticatedUUsernameRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VVideoIdRoute: VVideoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
